# Ko configuration for building QMux container images
# See: https://ko.build/configuration/

defaultBaseImage: gcr.io/distroless/static

defaultPlatforms:
  - all

builds:
  - id: qmux
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags '-static'
      - -X github.com/Mmx233/QMux/cmd.Version={{.Env.VERSION}}
