# Ko configuration for building QMux container images
# See: https://ko.build/configuration/

# Target platforms for multi-architecture builds
defaultPlatforms:
  - linux/amd64
  - linux/arm64
  - linux/arm/v7
  - linux/386
  - linux/ppc64le
  - linux/s390x

builds:
  - id: qmux
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -trimpath
      - -extldflags '-static'
      - -X github.com/Mmx233/QMux/cmd.Version={{.Env.VERSION}}
