{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "qmux.fullname" . }}
  labels:
    {{- include "qmux.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "qmux.selectorLabels" . | nindent 6 }}
  podTargetLabels:
    - app.kubernetes.io/instance
    - app.kubernetes.io/component
  podMetricsEndpoints:
    - port: admin
      path: /metrics
      interval: {{ .Values.podMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout | quote }}
      honorLabels: true
{{- end }}
